//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Function performed by an asset.
    public class AssetFunction : IdentifiedObject {
        
        /// Configuration specified for this function.
        private string cim_configID;
        
        private const bool isConfigIDMandatory = false;
        
        private const string _configIDPrefix = "cim";
        
        /// Firmware version.
        private string cim_firmwareID;
        
        private const bool isFirmwareIDMandatory = false;
        
        private const string _firmwareIDPrefix = "cim";
        
        /// Hardware version.
        private string cim_hardwareID;
        
        private const bool isHardwareIDMandatory = false;
        
        private const string _hardwareIDPrefix = "cim";
        
        /// Password needed to access this function.
        private string cim_password;
        
        private const bool isPasswordMandatory = false;
        
        private const string _passwordPrefix = "cim";
        
        /// Name of program.
        private string cim_programID;
        
        private const bool isProgramIDMandatory = false;
        
        private const string _programIDPrefix = "cim";
        
        public virtual string ConfigID {
            get {
                return this.cim_configID;
            }
            set {
                this.cim_configID = value;
            }
        }
        
        public virtual bool ConfigIDHasValue {
            get {
                return this.cim_configID != null;
            }
        }
        
        public static bool IsConfigIDMandatory {
            get {
                return isConfigIDMandatory;
            }
        }
        
        public static string ConfigIDPrefix {
            get {
                return _configIDPrefix;
            }
        }
        
        public virtual string FirmwareID {
            get {
                return this.cim_firmwareID;
            }
            set {
                this.cim_firmwareID = value;
            }
        }
        
        public virtual bool FirmwareIDHasValue {
            get {
                return this.cim_firmwareID != null;
            }
        }
        
        public static bool IsFirmwareIDMandatory {
            get {
                return isFirmwareIDMandatory;
            }
        }
        
        public static string FirmwareIDPrefix {
            get {
                return _firmwareIDPrefix;
            }
        }
        
        public virtual string HardwareID {
            get {
                return this.cim_hardwareID;
            }
            set {
                this.cim_hardwareID = value;
            }
        }
        
        public virtual bool HardwareIDHasValue {
            get {
                return this.cim_hardwareID != null;
            }
        }
        
        public static bool IsHardwareIDMandatory {
            get {
                return isHardwareIDMandatory;
            }
        }
        
        public static string HardwareIDPrefix {
            get {
                return _hardwareIDPrefix;
            }
        }
        
        public virtual string Password {
            get {
                return this.cim_password;
            }
            set {
                this.cim_password = value;
            }
        }
        
        public virtual bool PasswordHasValue {
            get {
                return this.cim_password != null;
            }
        }
        
        public static bool IsPasswordMandatory {
            get {
                return isPasswordMandatory;
            }
        }
        
        public static string PasswordPrefix {
            get {
                return _passwordPrefix;
            }
        }
        
        public virtual string ProgramID {
            get {
                return this.cim_programID;
            }
            set {
                this.cim_programID = value;
            }
        }
        
        public virtual bool ProgramIDHasValue {
            get {
                return this.cim_programID != null;
            }
        }
        
        public static bool IsProgramIDMandatory {
            get {
                return isProgramIDMandatory;
            }
        }
        
        public static string ProgramIDPrefix {
            get {
                return _programIDPrefix;
            }
        }
    }
}
